#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: ./stop.sh [all | tracker | storager | access]"
    exit 1
fi

if [ $1 = "all" ]; then
    pkill sdfs.
    exit 0
fi

if [ $1 = "tracker" ]; then
    pkill sdfs.trac
    exit 0
fi

if [ $1 = "storager" ]; then
    pkill sdfs.stora
    exit 0
fi

if [ $1 = "access" ]; then
    pkill sdfs.acc
    exit 0
fi
